version: '3.4'

services:
  honeypotpi:
    image: honeypotpi
    build:
      context: .
      dockerfile: ./Dockerfile

networks:
  my_network1:
    driver: bridge
    ports:
      - 63599:63599
      - 11535:11535
  host:
    driver: host
    ports:
      - 11535:11535
      - 8080:8080